# Redis配置
redis:
  host: 127.0.0.1
  port: 6379
  password: 
  db: 15

# MySQL配置
mysql:
  host: localhost
  port: 3306
  username: root
  password: null
  database: null

# MongoDB配置
mongodb:
  host: 127.0.0.1
  port: 27017
  username: root
  password: localtest
  database: web-wechat

# OSS配置
oss:
  endpoint: 127.0.0.1:9000
  accessKeyId: teaser
  accessKeySecret: localtest
  bucket: wechat
  ssl: false

# ChatGPT配置
openai:
  enable: false
  apikey: xxxx # 在 https://beta.openai.com/account/api-keys 申请
  proxy: http://127.0.0.1:7890 # 代理
